// Auto-generated by Spec2DV
// Minimal UVM register model stubs (skeleton)

`ifndef SPEC2DV_UVM_REGMODEL_SV
`define SPEC2DV_UVM_REGMODEL_SV

// NOTE: Requires UVM in a real environment.
// import uvm_pkg::*; `include "uvm_macros.svh"

// timer.TMR_CTRL @ offset 0x0
class timer_tmr_ctrl; // extends uvm_reg
  // uvm_reg_field fields[$];
  function void build();
    // EN [0:0] access=RW reset=0 width=1
    // MODE [2:1] access=RW reset=0 width=2
    // RSVD [31:3] access=RO reset=0 width=29
  endfunction
endclass

`endif